## Topics 
numpy  \
pandas  \
mdata processing

In [7]:
import pandas as pd

## 1. Load CSV File

Load employees.csv into a DataFrame.

Concepts:

pd.read_csv()

DataFrame basics

In [8]:
df = pd.read_csv('data.csv')

## 2. Display First and Last Rows

Display:

first 5 rows

last 3 rows

In [5]:
df.head(5)

   id   name  age   department  salary       city
0   1   Aman   25  Engineering   60000     Mumbai
1   2  Rahul   30           HR   50000       Pune
2   3   Neha   28  Engineering   70000  Bangalore
3   4  Priya   35      Finance   80000     Mumbai
4   5  Karan   22  Engineering   45000       Pune

In [6]:
df.tail(3)

   id   name  age   department  salary       city
5   6  Sneha   29           HR   52000      Delhi
6   7  Arjun   40      Finance   90000  Bangalore
7   8   Riya   27  Engineering   65000     Mumbai

## 3. Get Dataset Information

Find:

number of rows

number of columns

data types

In [8]:
df.shape

(8, 6)

In [9]:
df.dtypes

id             int64
name          object
age            int64
department    object
salary         int64
city          object
dtype: object

## 4. Select Specific Columns

Display only:

name
salary

In [12]:
df[['name','salary']]

    name  salary
0   Aman   60000
1  Rahul   50000
2   Neha   70000
3  Priya   80000
4  Karan   45000
5  Sneha   52000
6  Arjun   90000
7   Riya   65000

## 5. Filter Employees by Department

Find employees from:

Engineering

In [14]:
df[df['department'] == 'Engineering']

   id   name  age   department  salary       city
0   1   Aman   25  Engineering   60000     Mumbai
2   3   Neha   28  Engineering   70000  Bangalore
4   5  Karan   22  Engineering   45000       Pune
7   8   Riya   27  Engineering   65000     Mumbai

## 6. Filter Salary Greater than 60000

Output employees whose salary is greater than 60000.

In [15]:
df[df['salary'] > 60000]

   id   name  age   department  salary       city
2   3   Neha   28  Engineering   70000  Bangalore
3   4  Priya   35      Finance   80000     Mumbai
6   7  Arjun   40      Finance   90000  Bangalore
7   8   Riya   27  Engineering   65000     Mumbai

## 7. Find Average Salary

Calculate:

average salary

In [20]:
df['salary'].mean()

np.float64(64000.0)

## 8. Find Maximum Salary

`Output employee with highest salary.

In [24]:
df[df['salary'] == df['salary'].max()]

   id   name  age department  salary       city
6   7  Arjun   40    Finance   90000  Bangalore

## 9. Group By Department

Find average salary by department.

Concept:

groupby()

Expected output:

Engineering → avg salary
HR → avg salary
Finance → avg salary

In [33]:
df.groupby('department')['salary'].mean()

department
Engineering    60000.0
Finance        85000.0
HR             51000.0
Name: salary, dtype: float64

## 10. Count Employees per City

Find how many employees belong to each city.

In [35]:
df['city'].value_counts()

city
Mumbai       3
Pune         2
Bangalore    2
Delhi        1
Name: count, dtype: int64

## 11. Sort by Salary

Sort employees by salary descending.

In [40]:
df.sort_values(by='salary',ascending=False)

   id   name  age   department  salary       city
6   7  Arjun   40      Finance   90000  Bangalore
3   4  Priya   35      Finance   80000     Mumbai
2   3   Neha   28  Engineering   70000  Bangalore
7   8   Riya   27  Engineering   65000     Mumbai
0   1   Aman   25  Engineering   60000     Mumbai
5   6  Sneha   29           HR   52000      Delhi
1   2  Rahul   30           HR   50000       Pune
4   5  Karan   22  Engineering   45000       Pune

## 12. Create New Column

Create new column:

salary_after_bonus

Bonus = 10%

Example:

salary * 1.10

In [43]:
df['salary_after_bonus'] = (df['salary']*1.10).astype(int)

In [44]:
df

   id   name  age   department  salary       city  salary_after_bonus
0   1   Aman   25  Engineering   60000     Mumbai               66000
1   2  Rahul   30           HR   50000       Pune               55000
2   3   Neha   28  Engineering   70000  Bangalore               77000
3   4  Priya   35      Finance   80000     Mumbai               88000
4   5  Karan   22  Engineering   45000       Pune               49500
5   6  Sneha   29           HR   52000      Delhi               57200
6   7  Arjun   40      Finance   90000  Bangalore               99000
7   8   Riya   27  Engineering   65000     Mumbai               71500

## 13. Handle Missing Values

Modify dataset by adding missing value:

salary = NaN

Tasks:

detect missing values

fill missing values with average salary

Concepts:

isnull()
fillna()

In [58]:
import numpy as np
df.loc[df['id']>5, 'salary'] = np.nan

In [59]:
df

   id   name  age   department   salary       city  salary_after_bonus
0   1   Aman   25  Engineering  60000.0     Mumbai               66000
1   2  Rahul   30           HR  50000.0       Pune               55000
2   3   Neha   28  Engineering  70000.0  Bangalore               77000
3   4  Priya   35      Finance  80000.0     Mumbai               88000
4   5  Karan   22  Engineering      NaN       Pune               49500
5   6  Sneha   29           HR      NaN      Delhi               57200
6   7  Arjun   40      Finance      NaN  Bangalore               99000
7   8   Riya   27  Engineering      NaN     Mumbai               71500

In [61]:
df.isnull().sum()

id                    0
name                  0
age                   0
department            0
salary                4
city                  0
salary_after_bonus    0
dtype: int64

In [70]:
df['salary'] =  df['salary'].fillna(df['salary'].mean())

In [71]:
df

   id   name  age   department   salary       city  salary_after_bonus
0   1   Aman   25  Engineering  60000.0     Mumbai               66000
1   2  Rahul   30           HR  50000.0       Pune               55000
2   3   Neha   28  Engineering  70000.0  Bangalore               77000
3   4  Priya   35      Finance  80000.0     Mumbai               88000
4   5  Karan   22  Engineering  65000.0       Pune               49500
5   6  Sneha   29           HR  65000.0      Delhi               57200
6   7  Arjun   40      Finance  65000.0  Bangalore               99000
7   8   Riya   27  Engineering  65000.0     Mumbai               71500

## 14. Apply Function to Column

Convert names to uppercase.

In [73]:
df['name'] = df['name'].apply(lambda x:x.upper())

In [74]:
df

   id   name  age   department   salary       city  salary_after_bonus
0   1   AMAN   25  Engineering  60000.0     Mumbai               66000
1   2  RAHUL   30           HR  50000.0       Pune               55000
2   3   NEHA   28  Engineering  70000.0  Bangalore               77000
3   4  PRIYA   35      Finance  80000.0     Mumbai               88000
4   5  KARAN   22  Engineering  65000.0       Pune               49500
5   6  SNEHA   29           HR  65000.0      Delhi               57200
6   7  ARJUN   40      Finance  65000.0  Bangalore               99000
7   8   RIYA   27  Engineering  65000.0     Mumbai               71500

## 15. Filter Multiple Conditions

Find employees:

department = Engineering
salary > 60000

In [81]:
df[(df['department'] == 'Engineering') & (df['salary'] > 60000)]

   id   name  age   department   salary       city  salary_after_bonus
2   3   NEHA   28  Engineering  70000.0  Bangalore               77000
4   5  KARAN   22  Engineering  65000.0       Pune               49500
7   8   RIYA   27  Engineering  65000.0     Mumbai               71500

## 16. Merge Two DataFrames

Create another dataset departments.csv.

department,manager
Engineering,Rohit
HR,Anita
Finance,Suresh

Merge with employees dataset.

Concept:

merge()

In [85]:
df2 = pd.read_csv('department.csv')
df2

    department manager
0  Engineering   Rohit
1           HR   Anita
2      Finance  Suresh

In [84]:
pd.merge(df,df2, on='department')

   id   name  age   department   salary       city  salary_after_bonus manager
0   1   AMAN   25  Engineering  60000.0     Mumbai               66000   Rohit
1   2  RAHUL   30           HR  50000.0       Pune               55000   Anita
2   3   NEHA   28  Engineering  70000.0  Bangalore               77000   Rohit
3   4  PRIYA   35      Finance  80000.0     Mumbai               88000  Suresh
4   5  KARAN   22  Engineering  65000.0       Pune               49500   Rohit
5   6  SNEHA   29           HR  65000.0      Delhi               57200   Anita
6   7  ARJUN   40      Finance  65000.0  Bangalore               99000  Suresh
7   8   RIYA   27  Engineering  65000.0     Mumbai               71500   Rohit

In [89]:
df['city_dummy'] = df['city']

In [90]:
df

,id,name,age,department,salary,city,salary_after_bonus,city_dummy
0,1,AMAN,25,Engineering,60000.0,Mumbai,66000,Mumbai
1,2,RAHUL,30,HR,50000.0,Pune,55000,Pune
2,3,NEHA,28,Engineering,70000.0,Bangalore,77000,Bangalore
3,4,PRIYA,35,Finance,80000.0,Mumbai,88000,Mumbai
4,5,KARAN,22,Engineering,65000.0,Pune,49500,Pune
5,6,SNEHA,29,HR,65000.0,Delhi,57200,Delhi
6,7,ARJUN,40,Finance,65000.0,Bangalore,99000,Bangalore
7,8,RIYA,27,Engineering,65000.0,Mumbai,71500,Mumbai

In [99]:
del df['city_dummy']

In [104]:
df.loc[8]=df.iloc[7].to_dict()

In [105]:
df

   id   name  age   department   salary       city  salary_after_bonus
0   1   AMAN   25  Engineering  60000.0     Mumbai               66000
1   2  RAHUL   30           HR  50000.0       Pune               55000
2   3   NEHA   28  Engineering  70000.0  Bangalore               77000
3   4  PRIYA   35      Finance  80000.0     Mumbai               88000
4   5  KARAN   22  Engineering  65000.0       Pune               49500
5   6  SNEHA   29           HR  65000.0      Delhi               57200
6   7  ARJUN   40      Finance  65000.0  Bangalore               99000
7   8   RIYA   27  Engineering  65000.0     Mumbai               71500
8   8   RIYA   27  Engineering  65000.0     Mumbai               71500

## 17. Remove Duplicate Rows

Add duplicate row and remove it.

Concept:

drop_duplicates()

In [106]:
df.drop_duplicates()

   id   name  age   department   salary       city  salary_after_bonus
0   1   AMAN   25  Engineering  60000.0     Mumbai               66000
1   2  RAHUL   30           HR  50000.0       Pune               55000
2   3   NEHA   28  Engineering  70000.0  Bangalore               77000
3   4  PRIYA   35      Finance  80000.0     Mumbai               88000
4   5  KARAN   22  Engineering  65000.0       Pune               49500
5   6  SNEHA   29           HR  65000.0      Delhi               57200
6   7  ARJUN   40      Finance  65000.0  Bangalore               99000
7   8   RIYA   27  Engineering  65000.0     Mumbai               71500

## 18. Save DataFrame to CSV

After transformation save to:

processed_employees.csv

Concept:

to_csv()

In [107]:
df.to_csv('output.csv')

## 19. Convert DataFrame to Dictionary

Convert dataset to Python dictionary.

Concept:

to_dict()

In [108]:
df.to_dict()

{'id': {0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 8},
 'name': {0: 'AMAN',
  1: 'RAHUL',
  2: 'NEHA',
  3: 'PRIYA',
  4: 'KARAN',
  5: 'SNEHA',
  6: 'ARJUN',
  7: 'RIYA',
  8: 'RIYA'},
 'age': {0: 25, 1: 30, 2: 28, 3: 35, 4: 22, 5: 29, 6: 40, 7: 27, 8: 27},
 'department': {0: 'Engineering',
  1: 'HR',
  2: 'Engineering',
  3: 'Finance',
  4: 'Engineering',
  5: 'HR',
  6: 'Finance',
  7: 'Engineering',
  8: 'Engineering'},
 'salary': {0: 60000.0,
  1: 50000.0,
  2: 70000.0,
  3: 80000.0,
  4: 65000.0,
  5: 65000.0,
  6: 65000.0,
  7: 65000.0,
  8: 65000.0},
 'city': {0: 'Mumbai',
  1: 'Pune',
  2: 'Bangalore',
  3: 'Mumbai',
  4: 'Pune',
  5: 'Delhi',
  6: 'Bangalore',
  7: 'Mumbai',
  8: 'Mumbai'},
 'salary_after_bonus': {0: 66000,
  1: 55000,
  2: 77000,
  3: 88000,
  4: 49500,
  5: 57200,
  6: 99000,
  7: 71500,
  8: 71500}}

## 20. Top 3 Highest Paid Employees

Find top 3 salaries.

Concept:

nlargest()

In [10]:
df.sort_values(by='salary').tail(3)

   id   name  age   department  salary       city
2   3   Neha   28  Engineering   70000  Bangalore
3   4  Priya   35      Finance   80000     Mumbai
6   7  Arjun   40      Finance   90000  Bangalore

In [122]:
df = df[~(df['salary']<50000)]

In [128]:
df.groupby('department').value_counts()

department   id  name   age  salary  city
Engineering  1   Aman   25   60000   Mumbai       1
             3   Neha   28   70000   Bangalore    1
             8   Riya   27   65000   Mumbai       1
Finance      4   Priya  35   80000   Mumbai       1
             7   Arjun  40   90000   Bangalore    1
HR           2   Rahul  30   50000   Pune         1
             6   Sneha  29   52000   Delhi        1
Name: count, dtype: int64